server:
  port: 9000
spring:
  application:
    name: TaskAPI
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: "http://localhost/4200/"
          allowedMethods: "POST"
          allowedHeaders: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true

