server:
  port: 8022
spring:
  data:
    mongodb:
      database: taskCardDetail
      #spring.data.mongodb.uri = ${MONGO_URL}
      uri: mongodb://localHost:27017/
  application:
    name: taskCard-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true